import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import Header from "@/app/header";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { cookies } from "next/headers";
import { authQueries } from "@/features/auth/queries";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const cookieStore = await cookies();
  await queryClient.prefetchQuery(
    authQueries.me({ headers: { Cookie: cookieStore.toString() } }),
  );

  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} flex min-h-screen flex-col antialiased`}
      >
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />
          </HydrationBoundary>
          <main className="flex flex-1 flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
